### ISSUE TITLE
Order email not being send with certain configurations

### ISSUE THREAD

**Issue by hostep** [MultiSafepay/Magento2Msp#64] opened 2018-02-16 14:59 UTC
Hi guys

Using:
- Magento CE 2.1.11
- MultiSafepay 1.4.8
- Test Account

About the configuration 'When send the order confirmation e-mail'.

When picking the option 'When placing the order', emails are getting send out, that one works ok (but sends it too soon obviously)
When picking the option 'After transaction' or 'After paid transaction', no email is getting send out

I'm pretty sure this used to work, but now it no longer works.
We have reports that the same bug exists in version 1.3.0 of MultiSafepay, but I haven't verified that yet.

Thanks!

**Comment by Jasper-MultiSafepay** [comment] 2018-02-16 15:37
We have tested this on our test environments, but the emails are being send out.
If you send an email to techsupport@multisafepay.com we could investigate this on your staging environment.

**Comment by duckchip** [comment] 2018-05-02 13:07
I'd like to reopen this issue since I can reproduce the problem @hostep described. 

I was able to reproduce it on my local environment in **production** mode using the latest version 1.4.9 and Magento Commerce 2.2.2 .
On developer mode, everything seems to be working fine. 

The only way on how I get it working in production mode on my local is to set breakpoints in PHPStorm and get inside the functions on:
- line 87 of MultiSafepay\Connect\Controller\Connect\Success 
- line 59 of Magento\Sales\Model\AbstractNotifier

I think the issue might be the result of using the Object Manager instead of dependency injection.

**Comment by Jasper-MultiSafepay** [comment] 2018-05-02 13:53
Ok, issue reopened for investigation.
There are plans to use DI instead of the ObjectManager, but I cannot communicate when that's done.
I will try to reproduce this issue using the new described steps, will report back to you when I have results.

**Comment by duckchip** [comment] 2018-05-24 09:15
Hi @jasper-multisafepay 

Any news on this issue? 

Kind regards

**Comment by Jasper-MultiSafepay** [comment] 2018-05-24 14:42
@duckchip 
We have tried reproducing your steps on different version of Magento2 with production/developer mode switched, but we cannot reproduce this.
- Could you confirm "When send the order confirmation e-mail" was set to "After paid transaction"?
- Would you have a staging environment available where we could investigate this further?

**Comment by duckchip** [comment] 2018-06-08 09:37
@jasper-multisafepay 
We can confirm that "When send the order confirmation e-mail" is set to "After paid transaction"

We don't have a staging environment available at the moment.

good to know: 
- We're running on the latest version of the module: 1.5.0
- This problem only occurs with guest checkout

**Comment by kaybeudeker** [comment] 2018-06-08 09:49
Subscribed to this thread; we don't have this issue on a live/production server with CE 2.2.2 and 1.4.9 and/or 1.5.0 of the MSP extension while we **only** allow guest checkouts.

**Comment by hostep** [comment] 2018-06-08 10:51
Yeah, it's really strange, on some shops we have had the issue, and then suddenly it goes away and everything works properly, while nothing has changed.

We first thought it was because we had setup asynchronous sending of emails and that the cronjobs were perhaps not working correctly, but we've also seen it happen when the asynchronous sending of emails is disabled.

Still no idea what causes this.

**Comment by Jasper-MultiSafepay** [comment] 2018-06-08 12:46
I have created a quick workaround based on 1.5.0, but without being able to reproduce I cannot tell if this working.
Have replaced the OrderNotifier call with the OrderSender call, while forcing the email to be sent.
I would like to know if this solves anything, but use at own risk, recommend a staging environment.
https://github.com/jasper-multisafepay/Magento2Msp/commit/a37967a710ab47a8da47c807c85e268df91b5329

**References**
https://github.com/magento/magento2/blob/2.2/app/code/Magento/Sales/Model/AbstractNotifier.php#L56
https://github.com/magento/magento2/blob/2.2/app/code/Magento/Sales/Model/Order/Email/Sender/OrderSender.php#L97

**Comment by hostep** [comment] 2018-07-03 12:38
Hi Jasper

Just tested your patch, it doesn't seem to work.

I still don't understand this problem. This pops up ever so often out of nowhere on a shop where it used to work and now it doesn't anymore ...

Sending mails from an order with Banktransfer or any other payment method works perfectly fine.
Async email sending is disabled just to be sure it's not because of failing cronjobs.
Nothing to see in any log file. (sometimes I see a `No such entity with cartId =` or `Geen dergelijke entiteit met cartId =` message in the `system.log` file, but it doesn't always appear with every order, so that's probably something else, but not exactly sure...)

We have the problem now on at least 3 different shops, sometimes it works, sometimes not, and I don't understand why.
Maybe it's because of a conflict with a custom module, since most of our shops run the same modules, but it's really hard to determine what it would be exactly ...

**Comment by Jasper-MultiSafepay** [comment] 2018-07-03 15:11
@hostep 
If it happens sporadically, we would need to add some logging to our plugin and core Magento2.
Would you have an identical staging environment for us to do some research on?
According to https://github.com/magento/magento2/issues/13466 even when you disable async, it will still call async code, could be something.

**Comment by kaybeudeker** [comment] 2018-09-28 06:33
Any news/updates regarding this issue?

**Comment by Robert-MultiSafepay** [comment] 2019-09-24 15:20
At the moment we are going through our backlog and are analysing this 'Open' issue.
Unfortunately, we cannot reproduce the issue anymore, so we will close it hereby.

If you are still experiencing this specific issue, you can re-open and reply in the comment section,
or email to integration@multisafepay.com

**Closed as completed by Robert-MultiSafepay** 2019-09-24 15:20 UTC
Labels: cannot reproduce
