### ISSUE TITLE
"Banktransfer" Payment Method Not Working. All other payment methods are working fine.

### ISSUE THREAD

**Issue by Sonal824** [MultiSafepay/Magento2Msp#71] opened 2018-06-25 13:29 UTC
I am using Multisafe plugin for my Magento site.
All payment method are working fine except "Banktransfer"

During Checkout if i select "Banktransfer" and place an order then, it is redirecting me back to Cart page with following error.

https://www.screencast.com/t/OjyLTPRSOqu

System Info:
Magento version : 2.2.3
Multisafe pay version : 1.4.9

Thanks.

**Comment by Jasper-MultiSafepay** [comment] 2018-06-26 09:00
Could you send an email to techsupport@multisafepay.com with your accountID?
Most likely being caused by the banktransfer payment method being disabled, but would like to check.

**Comment by Sonal824** [comment] 2018-06-26 11:24
@jasper-multisafepay sent an email.

**Comment by Jasper-MultiSafepay** [comment] 2018-06-26 11:40
Received and replied.
Banktransfer is disabled on the account, closing this issue.
Can be enabled within our dashboard

**Closed as completed by Jasper-MultiSafepay** 2018-06-26 11:40 UTC
