### ISSUE TITLE
Cannot set extra fee for a payment method

### ISSUE THREAD

**Issue by GuidoHub** [MultiSafepay/Magento2Msp#47] opened 2017-10-25 14:32 UTC
In Magento 1 and Virtuemart plugin it was possible to set an extra fee for a specific payment method, in Magento 2 this option is not available.

**Comment by JonkRuud** [comment] 2017-10-26 09:38
@GuidoHub  For Magento 2 this is by design as we wanted to separate this functionality from the Magento 2 payment extension to provide better support and compatibility. We are working on a payment fee extension for our payment extension at https://github.com/MultiSafepay/Multisafepay-Magento-2-Payment-Fee

**Comment by GuidoHub** [comment] 2017-10-26 14:37
@JonkRuud  Oke, but is there any progress in this? It's a major downgrade compared to all other plugins. There is no way I can calculated a fee now. You can imagine that my costs are increasing now because of this choice. Can I contact your sales so they can arrange a payback of the extra costs? :)

**Comment by JonkRuud** [comment] 2017-10-27 06:49
@GuidoHub  its still in development and being worked on. As a test you could try the development version on a staging environment to see if its already working for you. Another way of adding af fee for now would be by using a third party extension for this.

**Comment by henk-hypershop** [comment] 2017-11-15 13:34
@GuidoHub Facing same issue here. My client cannot use 'Achteraf betalen' and module is still in beta. Does not seem to be any progress. What is the expected timeline to release a stable version?

**Comment by JonkRuud** [comment] 2017-11-16 13:29
At the moment there is no timeline set, and internally there is work done on the payment fee extension. To speed things up we are also working on compatibility with third party extensions like the fooman surcharge extension for Magento 2.

**Comment by JonkRuud** [comment] 2017-11-27 08:36
@GuidoHub @henk-hypershop  release 1.4.7 now has support for processing payment fee's by using Fooman Surcharge. https://store.fooman.co.nz/magento-extension-payment-surcharge-m2.html . We will keep on working on our own integration, but until that is finished we will support/integrate third party extensions for processing a payment fee. We will close this ticket and if needed continue in the repository of our fee extension.

**Closed as completed by JonkRuud** 2017-11-27 08:36 UTC
