### ISSUE TITLE
Double invoice for order v1.6.2.

### ISSUE THREAD

**Issue by thompalstra** [MultiSafepay/Magento2Msp#84] opened 2019-01-03 10:59 UTC
The plugins seems to receive multiple success notifications from the MSP API resulting in creating multiple invoices for the order. The notifications are always received within seconds from each other. 

![image](https://user-images.githubusercontent.com/17644484/50634395-c5171200-0f4e-11e9-8e70-8b2d5a0ebf9a.png)

Receiving a success status updates seems to (always) trigger a "create invoice" function, which is not necessary if the order already has the complete status.

**Comment by Jasper-MultiSafepay** [comment] 2019-01-04 14:34
@thompalstra 
Could you send me the merchant account ID to techsupport@multisafepay.com
So we can start debugging this?

**Comment by thlassche** [comment] 2019-04-09 07:28
I'm seeing this as well:

- Two notifications on the order status history
- One invoice, which is missing the amount of the second notification

**Comment by thlassche** [comment] 2019-04-29 20:09
@Jasper-MultiSafePay we just had another instance of this issue on M2.3.1, is there an update on this issue?

**Comment by Jasper-MultiSafepay** [comment] 2019-05-07 13:12
@thlassche 
We cannot reproduce this at our side.
Could you send an email to techsupport@multisafepay.com with the merchant account ID and screenshots/logs of the orders so we can debug this further?

**Comment by thlassche** [comment] 2019-05-07 16:52
@Jasper-MultiSafepay Found the issue, it's a core bug, I created a patch from this diff that fixes the issue:  https://github.com/magento/magento2/commit/ec2c6ca7df68de9aaccecfb899b102a2a3eaa631#diff-c56e8ff9758338ff84023146038824b9

Will most likely be fixed in 2.3.2

To replicate, order a bundle item and a simple item in the same order. On first notification from MSP an invoice for the bundle is created for the bundle only. Might be useful for you guys to know, if other customers run into this

**Comment by Jasper-MultiSafepay** [comment] 2019-05-08 07:05
@thlassche 
Nice find and thank you for notifying.

**Closed as completed** 2019-06-26 13:19 UTC
