### ISSUE TITLE
Undo cancel does not work due to getItemsCollection (magento 2.2.6)

### ISSUE THREAD

**Issue by lennartbee** [MultiSafepay/Magento2Msp#81] opened 2018-10-22 12:25 UTC
When a customer uncancels an order the order status remains 'pending' due to the orderitems that are still canceled. This happens in Magento 2.2.6. For some reason saving the orderitems in Connect.php does not work in combination with getItemsCollection. As a workaround I replaced line 1134 of Connect.php with:
`foreach ($order->getAllVisibleItems() as $item) {`
After this, the order items save again on uncancel. I do not know the exact difference with getItemsCollection and how this will affect uncancels with parent/child products.

**Comment by Jasper-MultiSafepay** [comment] 2018-10-22 13:04
I would not advise using getAllVisibleItems as it would only show parent products.
https://github.com/magento/magento2/blob/2.2/app/code/Magento/Sales/Model/Order.php#L1361

Seems to be caused by the additional save at
https://github.com/MultiSafepay/Magento2Msp/blob/1.6.1/Model/Connect.php#L1128
We're looking into this, but removing the save at line 1128 should also solve this.

**Comment by royvanos** [comment] 2018-10-23 11:22
We're experiencing this as well, we have to manually set qty_canceled and tax_canceled to 0 in the sales_order_item table to get rid of the canceled status for order items.

**Comment by Jasper-MultiSafepay** [comment] 2018-10-23 13:41
This issue is solved in the current release [1.6.2](https://github.com/MultiSafepay/Magento2Msp/releases/tag/1.6.2)
Could you perform an update of our plugin?

**Comment by JonkRuud** [comment] 2018-11-09 12:08
As this issue is solved in release 1.6.2 we will close this ticket.

**Closed as completed by JonkRuud** 2018-11-09 12:08 UTC
