### ISSUE TITLE
Compile error in version 1.5.1

### ISSUE THREAD

**Issue by GuidoHub** [MultiSafepay/Magento2Msp#73] opened 2018-08-31 13:33 UTC
Errors during compilation: MultiSafepay\Connect\Model\Connect
Incorrect dependency in class MultiSafepay\Connect\Model\Connect in /xxx/xxx/xxx/xxx/public_html/app/code/MultiSafepay/Connect/Model/Connect.php
\Magento\Framework\App\State already exists in context object
Total Errors Count: 1

**Comment by Jasper-MultiSafepay** [comment] 2018-09-03 10:42
@GuidoHub 
We are investigating this.
On which version of Magento2 are you encountering this?

**Comment by GuidoHub** [comment] 2018-09-03 12:56
@jasper-multisafepay It's on magento 2.1.14

**Comment by Jasper-MultiSafepay** [comment] 2018-09-03 14:19
Can reproduce this.
Being caused by context validation in Magento 2.1.x
This context validation is removed in Magento 2.2.x
Have added a solution to the current sprint of the plugin.
Sprint will be finished at the end of this month.
If needed I could make that branch public, so you can use the fix?

**Comment by GuidoHub** [comment] 2018-09-04 08:26
@jasper-multisafepay , would be nice if you could make it public so I can use the fix.

**Comment by Jasper-MultiSafepay** [comment] 2018-09-05 06:29
@GuidoHub 
Pushed branch 28c583645c33bee6cacfd451ec1eefcae7ed9016 for this compilation fix.
Will be added to the current sprint

**Comment by hostep** [comment] 2018-09-05 07:01
@jasper-multisafepay: wouldn't it make sense to release a hotfix where you include this fix, so a new version 1.5.2 with only the inclusion of this fix (if it is tested properly)?
I can imagine a lot of people updating to 1.5.1 running into this problem now. And waiting a full month for a fix is maybe a bit much?

(We haven't update ourselves yet, so I can't say if it will happen to us, but it sounds like it will when we do this on our Magento 2.1.x shops)

Thanks!

**Comment by Jasper-MultiSafepay** [comment] 2018-09-05 07:06
@hostep 
I'll have to discuss this internally if that's possible

**Comment by GuidoHub** [comment] 2018-09-05 11:10
@hostep I think you should also look at this issue #74

**Comment by Jasper-MultiSafepay** [comment] 2018-09-06 07:58
@hostep
I have received feedback on your request for a hotfix release:
The timing between a seperate hotfix release and the current sprint would be too short as it includes more extensive testing.
The next version (which also includes fixes for #73, #74) will be released no later than 21-9.

**Comment by hostep** [comment] 2018-09-06 08:04
Ok no problem, we'll hold of the upgrade for now on our 2.1 shops then.
Thanks for the feedback!

**Comment by Jasper-MultiSafepay** [comment] 2018-09-20 14:54
We released 1.6.0 which solves this issue.

**Closed as completed by Jasper-MultiSafepay** 2018-09-20 14:54 UTC
