### ISSUE TITLE
Stock inventory mixed up after second payment attempt

### ISSUE THREAD

**Issue by dragonfly4** [MultiSafepay/Magento2Msp#118] opened 2020-03-30 13:56 UTC
Magento 2.3.4
MultiSafePay 1.10.0
PHP 7.3.16

Salable quantity is higher than actual stock if customer completes payment in 2 attempts.

**Steps to reproduce**
- Place order on website. Magento reserves item in the database table inventory_reservation

| reservation_id | stock_id | sku | quantity | metadata |
| --- | --- | --- | --- | --- |
| 461 | 1 | GYBATH-400 | -1.0000 | `{"event_type":"order_placed","object_type":"order","object_id":"46687"}` |

- Customer is transferred to MultiSafePay
- Enter wrong card details or wrong verification code
- Payment is refused or cancelled

| reservation_id | stock_id | sku | quantity | metadata |
| --- | --- | --- | --- | --- |
| 464 | 1 | GYBATH-400 | 1.0000 | `{"event_type":"order_canceled","object_type":"order","object_id":"46687"}` |

- Customer tries again or uses the MSP Payment Link
- Payment is completed

> No changes in table inventory_reservation

- Order is processed and shipped. Inventory table is updated.

| reservation_id | stock_id | sku | quantity | metadata |
| --- | --- | --- | --- | --- |
| 719 | 1 | GYBATH-400 | 1.0000 | `{"event_type":"shipment_created","object_type":"order","object_id":"46687"}` |

- Salable quantity number is higher than actual stock. Inventory is mixed up.

Order comment log

> Notes for this Order
User redirected to MultiSafepay
Payment link:
https://payv2.multisafepay.com/connect/removedaaaWqWWOqOUguxmXW/?lang=nl_BE
Comment added Mar 29, 2020 12:58:43 PM

> Transaction declined
Comment added Mar 29, 2020 1:01:09 PM

> MultiSafepay status: completed
Notificatie ontvangen: Betaling vastgelegd voor 61,50 €. Transactie-ID: "343412464"
Comment added Mar 29, 2020 1:02:37 PM

> Order has been reopened because a new transaction was started by the customer!
Comment added Mar 29, 2020 1:02:37 PM

MSP Settings

![MSP_settings](https://user-images.githubusercontent.com/221351/77920492-d4deec80-729e-11ea-8e86-6fe41d4292b4.jpg)

**Comment by Jasper-MultiSafepay** [comment] 2020-03-30 14:00
@dragonfly4 
Thank you for reporting this.
Do you happen to use Multi Source Inventory?
We will try to reproduce this with the steps provided and investigate this further.
Will keep you updated.
PLGMAGTWOS-613

**Comment by dragonfly4** [comment] 2020-03-30 14:08
@Jasper-MultiSafepay 
Thanks! Let me know if you need more info.
We use one Inventory.
We do have 3 Store Views (nl - fr - en) referring to same orderid count as requested in #YED-254-52369. Ticket of 13/02/2020.

**Comment by Jasper-MultiSafepay** [comment] 2020-04-03 09:48
@dragonfly4 
A quick update, we can reproduce this at our side.
It is being caused by having to reopen orders, when a consumer tries again on a payment link.
Magento 2.3 calculates inventory/quantity/stock in a different way, which leads to our way of reopening orders isn't compatible now.
We are working on a solution, while staying compatible with Magento 2.2.
Will keep you updated.

**Comment by Jasper-MultiSafepay** [comment] 2020-04-24 14:10
@dragonfly4 
We now have a branch available which contains the cherry-picked changes.
In case you already would like to use this on a staging environment, you can checkout the changes.
https://github.com/MultiSafepay/Magento2Msp/compare/master...fix/stock-issues-reopen-orders

Or get the patch from
https://github.com/MultiSafepay/Magento2Msp/compare/master...fix/stock-issues-reopen-orders.patch

Or use composer
`composer require multisafepay/magento2msp:dev-fix/stock-issues-reopen-orders`

Next week we will have a release available, which will include this fix.

**Comment by duckchip** [comment] 2020-05-06 09:11
@Jasper-MultiSafepay Any idea when this release will be available?
thx!

**Comment by Jasper-MultiSafepay** [comment] 2020-05-06 20:31
@duckchip 
There was some internal feedback, but I'm expecting a release including this fix at the end of this week

**Comment by dragonfly4** [comment] 2020-05-06 21:10
My high level testing on DEV looked good so fingers crossed.

**Comment by vinodsowdagar** [comment] 2020-05-08 12:06
@dragonfly4 @duckchip 

The fix for this issue is now available in our latest release: https://github.com/MultiSafepay/Magento2Msp/releases/tag/1.12.0

For now i am closing this issue.
Please contact us again if you have any more feedback or questions regarding this matter.

**Closed as completed by vinodsowdagar** 2020-05-08 12:06 UTC
