### ISSUE TITLE
Frontend is showing payment method that is not selected in the Magento backend.

### ISSUE THREAD

**Issue by appdezign** [MultiSafepay/Magento2Msp#114] opened 2020-02-17 10:06 UTC
Magento2Msp version: 1.8.0
Magento version: 2.3.1

I have selected Credit Card as my gateway in the Magento Configuration, and I have selected two credit cards: visa and mastercard, the other two card are NOT selected (American Express and Maestro). I have checked the configuration on all configuration levels: website, store, view.

<img width="973" alt="msp-backend" src="https://user-images.githubusercontent.com/14594715/74642750-dda6b380-5173-11ea-885c-bf25015bfd7a.png">

When I go to the frontend, and I checkout, I get a select dropdown with all four credit card choices:

<img width="665" alt="msp-frontend" src="https://user-images.githubusercontent.com/14594715/74643119-7fc69b80-5174-11ea-9ac0-d955068f447f.png">

In the MultiSafePay backend I have also selected visa and mastercard, and not the other two, so if the user does select Maestro during checkout, in the next step (the actual payment page) he or she is then presented with only two choices: visa or mastercard. 

Is this a bug? Or am I missing something here.

**Comment by vinodsowdagar** [comment] 2020-02-17 12:32
Hi @appdezign ,

Thank you for reporting this issue.

This seems to be a bug which makes the credit cards always show in the dropdown menu, regardless of what has been chosen in the ‘Allowed credit cards’ field in the backend.

We have successfully reproduced this issue and we are going to work on a fix as soon as possible.

We will let you know when the fix for this issue will be ready.

**Comment by vinodsowdagar** [comment] 2020-05-08 13:13
Hi @appdezign 

We have released a change in the credit card payment gateway behaviour in our latest release:
https://github.com/MultiSafepay/Magento2Msp/releases/tag/1.12.0

On the MultiSafepay payment page, the credit card type will now be automatically detected, so the configuration option for allowing specific credit cards is not supported anymore. Therefore this has been removed.

For now i am closing this issue. If you have any further questions or feedback, please feel free to create a new one, or contact our integration team.

**Closed as completed by vinodsowdagar** 2020-05-08 13:13 UTC
Labels: bug
