### ISSUE TITLE
Select ideal issuer twice

### ISSUE THREAD

**Issue by marleenp1p5** [MultiSafepay/Magento2Msp#13] opened 2017-05-04 11:58 UTC
Hi,

When I want to checkout with iDeal I can select the issuer from te list on the checkout screen. When I proceed to payment, I have to select the issuer again.

Using MSP version 1.3.0 on magento 2.1.6

Best regards,
Marleen

**Comment by JonkRuud** [comment] 2017-05-04 12:36
Hello Marleen,
We couldn't reproduce this one on our dev/testing environments. Do you mind creating a technical support ticket for us by mailing to 'techsupport @ multisafepay.com' so we can get this one looked at on your environment?

**Comment by JonkRuud** [comment] 2017-05-15 07:53
Hello Marleen,

Did you create a ticket for this one, if so, was it resolved?

**Comment by JonkRuud** [comment] 2017-05-15 08:02
Hello Marleen, 

Just noticed that this was already fixed in the develop branch, but not yet released. If you still need the fix then you can checkout commit: https://github.com/MultiSafepay/Magento2Msp/commit/f158770fbae77f5c5bdfdf0248fe775ff4b2c559
Or wait for the next release and update it. We expect to release the next version this week.

**Closed as completed by JonkRuud** 2017-05-15 08:02 UTC
