### ISSUE TITLE
Customer-data.js error on success page

### ISSUE THREAD

**Issue by lery12** [MultiSafepay/Magento2Msp#46] opened 2017-10-18 09:59 UTC
Hi,

I installed this extension om magento 2.1.7 and when i activate the extension and try to complete a order. the success page (http://{HERE THE URL}.nl/nl/checkout/onepage/success?utm_nooverride=1/)  give a JS error.

customer-data.js on line 85,  Uncaught TypeError: Cannot read property 'sectionLoadUrl' of undefined.

When i complete order with the extension disabled and proces with cash on delivery every thing works just fine!

Is there a solution?

**Comment by Jasper-MultiSafepay** [comment] 2017-10-18 11:24
@lery12 
Seems to be caused by clearing the minicart through JS.
Will try to reproduce this and if so I will create an internal ticket for this to solve.

**Comment by lery12** [comment] 2017-10-18 11:45
Do i need to send some files, so you can try to reproduce?

**Comment by lery12** [comment] 2017-10-20 12:18
Hi Jasper,
Any luck with the reproduction of the error?

**Comment by Jasper-MultiSafepay** [comment] 2017-10-20 13:19
@lery12 
I can reproduce it, but not consistently.
Internal ticket has been created to see if we can clear the minicart in a different way without the JS error showing up in the console.

**Comment by JonkRuud** [comment] 2017-11-20 12:43
@lery12  this issue has been resolved within the develop branch and will be included within the next release this week

**Comment by JonkRuud** [comment] 2017-11-27 08:38
@lery12  release 1.4.7 is now online and includes the fix for this issue so we will close this ticket.

**Closed as completed by JonkRuud** 2017-11-27 08:38 UTC
