### ISSUE TITLE
Possibility to send a payment link to customer in staging mode?

### ISSUE THREAD

**Issue by melnickforever** [MultiSafepay/Magento2Msp#62] opened 2018-01-12 08:33 UTC
We updated msp to 1.4.8
We created order from magento backoffice. System in staging mode.
After 1 h we get email with text "Nieuwe kans" without payment link. Is this a feature of staging mode ?

**Comment by Jasper-MultiSafepay** [comment] 2018-01-12 09:48
We currently don't send a paymentlink, when you create a backend order.
But we do save the paymentlink in the order notes.
Also our systems send an email with the payment link after 1 hour, as a Second Chance feature.
If you could send an email to techsupport@multisafepay.com with your test accountID, I could investigate why the paymentlink was empty.

**Comment by JonkRuud** [comment] 2018-11-09 12:14
As the request was mentioned to go through our support channel and it seems to be a duplicate of https://github.com/MultiSafepay/Magento2Msp/issues/57 we will close this ticket.

**Closed as completed by JonkRuud** 2018-11-09 12:14 UTC
