### ISSUE TITLE
Paying with afterpay results in 2 invoices in Magento

### ISSUE THREAD

**Issue by dverkade** [MultiSafepay/Magento2Msp#123] opened 2020-06-21 14:07 UTC
Magento version: 2.3.5
MSP module version: 2.11.0

When an order is paid with afterpay 2 invoices are created. See screenshots below. The second invoice will have a total of 0.00 because there's nothing left to invoice. 

![image](https://user-images.githubusercontent.com/1058480/85226632-ca814a00-b3d8-11ea-9b98-fdaee9e4a8dd.png)

![image](https://user-images.githubusercontent.com/1058480/85226638-d4a34880-b3d8-11ea-9d8b-e167b71f4cdf.png)

![image](https://user-images.githubusercontent.com/1058480/85226673-103e1280-b3d9-11ea-8414-0f2ba19bcdf0.png)

**Comment by vinodsowdagar** [comment] 2020-06-22 08:19
Hi @dverkade ,

I am currently looking into this. 
We will keep you updated as soon as we know more about what is causing this issue.

**Comment by vinodsowdagar** [comment] 2020-06-22 14:22
Hi @dverkade ,

We were unable to reproduce this issue on a core Magento 2.3.5 environment, with the MultiSafepay plugin version 1.11.0.

We may be using settings other than yours, which has prevented us from reproducing the exact same situation.

That is why i would ask you for the following:
- Is it always the case that a double invoice is created with Afterpay, or did it only happen this time or sometimes?
- What type of products do the orders contain? (Bundled / Configurable / Simple)

You have also contacted us by e-mail via integration@multisafepay.com. I have sent you a reply on there as well.

**Comment by paulvandermeijs** [comment] 2020-07-28 08:34
Hello @Vinod-MultiSafepay,
We are experiencing the same issue. I have been trying to reproduce this in the test environment but have so far been unsuccessful (tried clicking the complete button twice and reloading the success page).

The issue doesn't seem to be restricted to Afterpay as for us it happened with iDEAL.

We've seen this problem occur with grouped products though we've also seen orders with grouped products where there weren't any problems. Also when multiple invoices are created both reference the same order and order item.

For orders where we are seeing this issue we're also seeing two status notifications in the order's comments:

![image](https://user-images.githubusercontent.com/513046/88640017-bc9ca400-d0bd-11ea-82a8-e3817225a495.png)


In our case though both invoices include the full amount.

![image](https://user-images.githubusercontent.com/513046/88639553-32ecd680-d0bd-11ea-8daa-30b97e66c32e.png)


We are using Magento 2.3.4-p2 and MSP module 1.10.0.

**Comment by vinodsowdagar** [comment] 2020-07-28 09:16
Hi @paulvandermeijs ,

We already resolved this issue for @dverkade via an e-mail ticket.

It seemed that @dverkade had this issue because he had installed another module that also added another Afterpay gateway. This module conflicted with our module and creates an invoice beforehand for our Afterpay gateway as well. I think this issue was fixed by turning off the other Afterpay module.

Edit:
If that is not the case for you, then maybe you can try to update to the latest version of the plugin: https://github.com/MultiSafepay/Magento2Msp/releases/tag/1.12.2

We fixed double invoices in that version as well.

**Comment by paulvandermeijs** [comment] 2020-07-28 11:13
Hello @Vinod-MultiSafepay,
We're not using any other PSP besides MultiSafepay but I'll update the module to see if it fixes the issue.

**Comment by vinodsowdagar** [comment] 2020-08-17 09:00
Hi @paulvandermeijs ,

Are you still experiencing this issue?

**Comment by magent-harsh** [comment] 2020-10-05 12:44
Hi
We have facing those two error
1 - getting duplicate order with same products
2 - out of stock products are place order with afterpay

**Comment by Jasper-MultiSafepay** [comment] 2020-10-06 08:24
@magent-harsh 
Can you send an email to integration@multisafepay.com
We would like to check with you what's happening and if it is not a conflict with another module.

**Closed as completed** 2020-11-17 08:52 UTC
